# Generated by Django 6.0.3 on 2026-04-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('issue_type', models.CharField(choices=[('Harassment', 'Harassment'), ('Bullying', 'Bullying'), ('Unsafe Environment', 'Unsafe Environment'), ('Discrimination', 'Discrimination'), ('Other', 'Other')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
