# Generated by Django 6.0.3 on 2026-04-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otp_mobile_alter_user_email_alter_user_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=15),
        ),
    ]
