# Generated by Django 6.0.3 on 2026-04-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='created_at',
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
