# Generated by Django 6.0.3 on 2026-04-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_of_use', models.IntegerField(blank=True, null=True)),
                ('emergency_response', models.IntegerField(blank=True, null=True)),
                ('legal_assistance', models.IntegerField(blank=True, null=True)),
                ('complaint_filing', models.IntegerField(blank=True, null=True)),
                ('nearby_help', models.IntegerField(blank=True, null=True)),
                ('overall_design', models.IntegerField(blank=True, null=True)),
                ('overall_experience', models.CharField(blank=True, max_length=20)),
                ('recommend', models.CharField(blank=True, max_length=20)),
                ('best_feature', models.CharField(blank=True, max_length=50)),
                ('improvement', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
